---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yipcbubw/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp ExquisiteCorpse.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp v1.3.0_arclight_release_notes.pdf $DEPLOYPATH
    - /bin/cp webdeveloper.php $DEPLOYPATH
    - /bin/cp writer.php $DEPLOYPATH
    - /bin/cp adroid-chrome-192x192.png $DEPLOYPATH
    - /bin/cp adroid-chrome-512x512.png $DEPLOYPATH
    - /bin/cp apple-touch-icon.png $DEPLOYPATH
    - /bin/cp favicon-16x16.png $DEPLOYPATH
    - /bin/cp favicon-32x32.png $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
